# Generated by Django 4.2 on 2023-05-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_alter_content_options_alter_module_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.FileField(upload_to="images"),
        ),
    ]
